channels:
  - conda-forge
  - default
dependencies:
  - python>=3.10.*
  - pip
  - cmake
  - compas
  - flask
  - numpy
  - pythonocc-core
  - freecad
  - pyopenssl
  - scipy=1.8.1
  - setuptools
  - shapely
  - wheel
  - ifcopenshell
  - pip:
      - cmake
      - boto3
      - yandexcloud
      - redis-py-cluster
      - setuptools_rust
      - redis
      - pottery
      - colored==1.4.3
      - compas-occ
      - fastapi
      - gh-io-stubs==7.7.21140
      - gh-util-stubs==7.7.21140
      - grasshopper-stubs==7.7.21140
      - jedi==0.18.1
      - orjson==3.8.0
      - pydantic
      - python-dotenv
      - python-multipart
      - pythreejs==2.4.1
      - rhino-stubs==7.7.21140
      - ujson==5.5.0
      - uvicorn
      - uvloop
      - fastapi[all]
prefix: $CONDA_PREFIX
